import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

//  ui
import styles from '../styles/Home.module.css';

import Header from '../components/Header';
import Masthead from '../components/Masthead';
import AboutUs from '../components/AboutUS/AboutUs';
import Skills from '../components/Skills/Skills';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Самара Кабель Монтаж</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Masthead />
      <AboutUs />
      <Skills />
      <Footer />
    </div>
  )
}

export default Home
